#!/usr/bin/env python3
"""
Generate outputs/attack_comparison/heatmap_figures.tex
Each of the 21 (token × position) groups becomes one figure:
  3 rows  = forward / reverse / combined
  5 cols  = repetition 1 … 5
"""
import pathlib

ROOT       = pathlib.Path(__file__).parent.parent
OUT_PATH   = ROOT / "outputs" / "attack_comparison" / "heatmap_figures.tex"
ATTACKS    = ROOT / "outputs" / "attacks"

TOKENS     = ["bar", "false", "important", "information", "relevance", "relevant", "true"]
POSITIONS  = ["end", "random", "start"]
REPS       = [1, 2, 3, 4, 5]
DIRECTIONS = [
    ("forward",  "forward_layer_component_heatmap.png"),
    ("reverse",  "reverse_layer_component_heatmap.png"),
    ("combined", "combined_layer_component_heatmap.png"),
]

IMG_W = r"0.17\textwidth"

lines = [
    r"% Auto-generated by scripts/generate_heatmap_figures_tex.py",
    r"% One figure per (token, position); 3 rows x 5 cols inside each figure.",
    "",
]

for token in TOKENS:
    for position in POSITIONS:
        group = f"{token}_{position}"
        label = f"fig:hm:{group}"

        lines.append(r"\begin{figure}[H]")
        lines.append(r"\centering")
        lines.append(r"\setlength{\tabcolsep}{2pt}")
        lines.append(r"\renewcommand{\arraystretch}{0.5}")
        lines.append(r"\begin{tabular}{r ccccc}")

        # column headers
        col_headers = " & ".join(rf"\textbf{{rep={r}}}" for r in REPS)
        lines.append(f"& {col_headers} \\\\[2pt]")

        for dir_label, png_name in DIRECTIONS:
            cells = []
            for rep in REPS:
                attack_name = f"{group}_{rep}"
                png_path = f"outputs/attacks/{attack_name}/plots/{png_name}"
                # check file exists (informational only – LaTeX will error if missing)
                full = ATTACKS / attack_name / "plots" / png_name
                if full.exists():
                    cells.append(rf"\includegraphics[width={IMG_W}]{{{png_path}}}")
                else:
                    cells.append(r"\fbox{\parbox[c][1.5cm][c]{" + IMG_W + r"}{\centering\tiny N/A}}")
            row = " & ".join(cells)
            rot = rf"\rotatebox{{90}}{{\textbf{{{dir_label}}}}}"
            lines.append(f"{rot} & {row} \\\\[4pt]")

        lines.append(r"\end{tabular}")
        lines.append(
            rf"\caption{{Patching heatmaps for \texttt{{{group}}}: "
            rf"forward (top), reverse (middle), combined (bottom) "
            rf"across repetitions 1--5.}}"
        )
        lines.append(rf"\label{{{label}}}")
        lines.append(r"\end{figure}")
        lines.append("")

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
OUT_PATH.write_text("\n".join(lines))
print(f"Written {len(lines)} lines → {OUT_PATH}")
